language: python
sudo: false
python:
  - "2.7"

cache:
  directories:
    - node_modules
    - $HOME/.cache/pip/

matrix:
  fast_finish: true
  include:
    - env: TOX_ENV=flake8
    - env: TOX_ENV=docs
    - env: TOX_ENV=assets
    - env: TOX_ENV=elasticsearch
    - env: TOX_ENV=main APP=abuse
    - env: TOX_ENV=main APP=accounts
    - env: TOX_ENV=main APP=addons
    - env: TOX_ENV=main APP=amo
    - env: TOX_ENV=main APP=api
    - env: TOX_ENV=main APP=bandwagon
    - env: TOX_ENV=main APP=blocklist
    - env: TOX_ENV=main APP=devhub
    - env: TOX_ENV=main APP=discovery
    - env: TOX_ENV=main APP=editors
    - env: TOX_ENV=main APP=files
    - env: TOX_ENV=main APP=landfill
    - env: TOX_ENV=main APP=lib
    - env: TOX_ENV=main APP=paypal
    - env: TOX_ENV=main APP=reviews
    - env: TOX_ENV=main APP=search
    - env: TOX_ENV=main APP=signing
    - env: TOX_ENV=main APP=stats
    - env: TOX_ENV=main APP=tags
    - env: TOX_ENV=main APP=translations
    - env: TOX_ENV=main APP=users
    - env: TOX_ENV=main APP=zadmin

services:
  - memcached

before_install:
  - scripts/travis_es.sh
  - /tmp/elasticsearch/elasticsearch-1.3.2/bin/elasticsearch -d -D es.path.data=/tmp -D es.gateway.type=none -D es.index.store.type=memory -D es.discovery.zen.ping.multicast.enabled=false

install:
  - pip install tox==2.3.1

before_script:
  - mysql -e 'create database olympia;'

script:
  - RUNNING_IN_CI=True tox -v -e $TOX_ENV

notifications:
  irc:
    channels:
      - "irc.mozilla.org#amo-bots"
    on_success: change
    on_failure: always

branches:
  only: [master]
